# SETUP
baseurl = "/"
publishdir = "public"
DefaultContentLanguage = "en"
canonifyUrls = "true"
disableKinds = ["RSS","taxonomy","taxonomyTerm"] #remove this if needed
summaryLength = 40

[outputs]
    home = ["HTML","RSS"]
    section  = ["HTML"]

[outputFormats]
    [outputFormats.RSS]
        mediatype = "application/rss"
        baseName = "feed"

# for RSS feed
[author]
    name = "darkweak"
    email = "darkweak@protonmail.com"

[params]
    author = "Sylvain COMBRAQUE"
    title = "devcv | Sylvain COMBRAQUE"
    description = "Sylvain COMBRAQUE - CV"
    showReadTime = 1
    images = ["https://avatars.githubusercontent.com/u/25440709?v=4"]

[social]
    twitter = "darkweak_dev"
