baseurl: https://devcv.fr/
publishdir: public
DefaultContentLanguage: en
canonifyUrls: true

languages:
  en:
    languageName: English
    weight: 1
    menu:
      navbar:
        - identifier: home
          name: Home
          url: /
          weight: 1
        - identifier: conferences
          name: Talks
          url: /conferences
          weight: 2
        - identifier: blog
          name: Blog
          url: /blog
          weight: 3
        - identifier: career
          name: Career
          url: /career
          weight: 4
        - identifier: skills
          name: Skills
          url: /skills
          weight: 5

  fr:
    languageName: Français
    weight: 2
    menu:
      navbar:
        - name: Accueil
          url: /
          weight: 1
        - name: Conférences
          url: /conferences
          weight: 2
        - name: Blog
          url: /blog
          weight: 3
        - name: Carrière
          url: /career
          weight: 4
        - name: Compétences
          url: /skills
          weight: 5
  es:
    languageName: Spanish
    weight: 3
    menu:
      navbar:
        - identifier: home
          name: Casa
          url: /

author:
  name: darkweak
  email: darkweak@protonmail.com

params:
  author: Sylvain COMBRAQUE
  title: devcv | Sylvain COMBRAQUE
  description: Sylvain COMBRAQUE - CV
  baseURL: https://devcv.fr/
  showReadTime: 1
  images:
    - https://avatars.githubusercontent.com/u/25440709?v=4

social:
  twitter: darkweak_dev
